title: "GSoC 2025 - Muhammad Salman"
description: "My final report and weekly updates for Google Summer of Code 2025"
theme: jekyll-theme-cayman

nav_order: 1
nav_links:
  - title: "Home"
    url: /
  - title: "Weekly Updates"
    url: /weekly-updates/
